img_root = "./data/image_data/images12_plus/"
batch_size = 64
# out_path = "./data/triplets/resnet50/avgpool/"
# model_name = "resnet50"
# module_name = "avgpool"

# barlowtwins-rn50

# out_path = "./data/triplets/barlowtwins-rn50/avgpool/"
# model_name = "barlowtwins-rn50"
# module_name = "avgpool"

# out_path = "./data/triplets/VGG16_ecoset/classifier.3"
# model_name = "VGG16_ecoset"
# module_name = "classifier.3"

# model_name = "densenet121"
# module_name = "global_pool"
# out_path = "./data/triplets/densenet/global_pool"

# model_name = "inception_v3"
# module_name = "avgpool"
# out_path = "./data/triplets/inception_v3/avgpool"

model_name = "vit_b_32"
module_name = "encoder.ln"
weights = "Imagenet1k"
out_path = "./data/features/"