# These are the configurations for the human DNN comparison!

# human_path_base = "./data/misc/vice_embedding_lukas_66d.txt"

human_path_base = "./results/sslab_behavior/behavior/4.12mio/sslab/300/256/0.85/0/params/params_epoch_2000.npz"
human_path_comp = "./results/sslab_behavior/behavior/4.12mio/sslab/300/256/0.85/1/params/params_epoch_2000.npz"

dnn_path = "results/sslab_final/deep/vgg16_bn/classifier.3/20.mio/sslab/300/256/0.24/0/params/parameters.npz"

triplet_path =  "./data/triplets/behavior"
img_root = "./data/image_data/images12_plus"

analysis_key = "val_loss"
evaluation_key = "beta"