human_embedding_path =  "./data/embeddings/human_behavior/"
dnn_embedding_path = "./data/embeddings/vgg16_bn/classifier.3/"

triplet_path = "./data/triplets/behavior"
img_root = "./data/images/things"
feature_path = "./data/features/vgg16_bn/classifier.3/"

[jackknife]
run_jackknife = true
plot = true
plot_relevance = true
comparison = "dnn"

[comparison]
diff_measure = "signed"

[residual]
k_folds = 5
run_search = true 

[rsa]
corr_type = "pearson"
concept_path = "./data/misc/category_mat_manual.tsv"
run_analysis = false