human_path =  "./results/behavior/variational/4.12mio/sslab/150/256/1.0/21/params/parameters.npz"
human_path_comp = "./results/behavior/variational/4.12mio/sslab/150/256/1.0/20/params/parameters.npz"
dnn_path = "./results/dnn/variational/vgg16_bn/classifier.3/20.mio/sslab/150/256/1.0/14/params/parameters.npz"

triplet_path = "./data/triplets/behavior"
img_root = "./data/image_data/images12_plus"
feature_path = "./data/triplets/Imagenet1k/vgg16_bn/classifier.3/"

[jackknife]
run_jackknife = false
plot = true
comparison = "dnn"

[comparison]
diff_measure = "signed"

[residual]
k_folds = 5
run_search = true 

[rsa]
corr_type = "pearson"
concept_path = "./data/misc/category_mat_manual.tsv"
run_analysis = true