embedding_path = "./data/embeddings/vgg16_bn/classifier.3/"
feature_path = "./data/features/vgg16_bn/classifier.3/"
img_root = "./data/images/things"
device = "cuda:0"
seed = 42

[visualization]
per_dim = true
filter_behavior = false
filter_plus = true
behav_experiment = false # if to viz for the behavioral study (large images)

# Sparse Code parameters
[linear_model]
k_folds = 3

# activation maximization parameters
[act_max]
sample_dataset = false
find_topk = false
optimize_topk = true
dim = [28,22,16,44,0,8,18, 19]      # dims to optimize
model_name = "vgg16_bn"
module_name = "classifier.3"
n_samples = 100_000
window_size = 40
batch_size = 64
truncation = 1.0
top_k = 16
max_iter = 100
alpha = 0.1
beta = 1.0
lr = 0.002
