
# These are for all 
[general]

# embedding_path="./embedding_256/params/embedding_epoch_500.txt"
# embedding_path="./embedding/1/params/parameters.npz"
embedding_path="./results/test/deep/vgg16_bn/classifier.3/20.mio/sslab/300/16384/0.1/0/params/params_epoch_2030.npz"


dnn_path="./data/triplets/vgg16_bn/classifier.3"
seed = 42
device = "cuda:0"
img_root = "./data/image_data/images12_plus"

[visualization]
per_dim = false
filter_behavior = false
filter_plus = true

# Sparse Code parameters
[sparse_codes]
k_folds = 3
feature_norm_path = "./data/feature_norms/feature_object_matrix.csv"

# Big GAN parameters
[big_gan]
model_name = "vgg16_bn"
module_name = "classifier.3"
n_samples = 2_000_000
window_size = 50
batch_size = 16
truncation = 0.4
top_k = 16
sample_latents= true
max_iter = 200
dim = [0,1,2,3]
alpha = 1.0
beta = 1.0

# GPT3 parameters
[gpt3]
feature_norm_path = "./data/feature_norms/feature_object_matrix.csv"

# Searchlight parameters
[searchlight]
feature_path = "./data/models/vgg16_bn/classifier.3/"
window_size = 20
stride = 1
analysis = "regression"