[general]

# embedding_path = "./results/residuals_dependent_dnn/behavior/4.12mio/sslab/150/256/1.0/4/params/params_epoch_1000.npz"
# embedding_path = "./results/residuals_dependent_human/behavior/4.12mio/sslab/150/256/1.0/4/params/parameters.npz"

# embedding_path = "./results/dnn/variational/vgg16_bn/classifier.3/20.mio/sslab/150/256/1.0/14/params/parameters.npz"
# embedding_path = "./results/behavior/variational/4.12mio/sslab/150/256/1.0/21/params/parameters.npz"

embedding_path = "./results/residuals_dependent_human_intersection/behavior/variational/4.12mio/sslab/150/256/1.0/0/params/params_epoch_650.npz"

# SPoSE embedding path
# embedding_path = "./results/spose_split/behavior/4.12mio/sslab/300/256/0.0037/0.0037/1/params/parameters.npz"
# embedding_path = "./data/misc/vice_embedding_lukas_66d.txt"

dnn_path = "./data/triplets/vgg16_bn/classifier.3"
img_root = "./data/image_data/images12_plus"
seed = 42
device = "cuda:0"

[visualization]
per_dim = false
filter_behavior = true
filter_plus = false
behav_experiment = false # if to viz for the behavioral study (large images)

# Sparse Code parameters
[sparse_codes]
k_folds = 3

# activation maximization parameters
[act_max]
sample_dataset = false
find_topk = false
optimize_topk = true
dim = [0,8,18, 19]      # dims to optimize

model_name = "vgg16_bn"
module_name = "classifier.3"
n_samples = 100_000
window_size = 40
batch_size = 64
truncation = 1.0
top_k = 16
max_iter = 100
alpha = 0.1
beta = 1.0
lr = 0.002


# GPT3 parameters
[gpt3]
feature_norm_path = "./data/feature_norms/feature_object_matrix.csv"
run = false 
