# Path parameters
log_path = "./results"
identifier = ""

# General parameters
triplet_path = "./data/things/triplets"
modality = "behavior" 
load_model = false
fresh = false
tensorboard = true
params_interval = 200
checkpoint_interval = 50  # we dont save the model in principle!
device_id = 0
method = "deterministic"

# Model parameters
init_dim = 90
n_epochs = 2000
stability_time = 500
seed = 0
batch_size = 100
beta = 0.00385 # same as lambda
lr = 0.001
