# Path parameters
log_path = "./results"
identifier = ""

# General parameters
triplet_path = "./data/triplets/behavior"
modality = "behavior" 
load_model = false
fresh = false
tensorboard = true
params_interval = 200
checkpoint_interval = 50  # we dont save the model in principle!
device_id = 0
method = "variational"

# Model parameters
prior = "sslab"
init_dim = 500
n_epochs = 10000
stability_time = 500
seed = 42
batch_size = 256
non_zero_weights = 5
mc_samples = 20
beta = 1.0
scale = 1.0
lr = 0.001
