# Path parameters
log_path = "./results"
identifier = "sslab_final"

# General parameters
triplet_path = "./data/triplets/vgg16_bn/classifier.3/triplets_20mio"
modality = "deep" 
load_model = true
fresh = false  
tensorboard = true
params_interval = 500
checkpoint_interval = 50  # we dont save the model in principle!
device_id = 0


# Model parameters
prior = "sslab"
init_dim = 500
n_epochs = 50000
stability_time = 2000
seed = 0
batch_size = 16384
non_zero_weights = 5
mc_samples = 20
beta = 1.0
scale = 1.0
lr = 0.001