# Path parameters
log_path = "./results"
identifier = "test"

# General parameters
load_model = true
fresh = false  
tensorboard = true

triplet_path = "./data/triplets/Imagenet1k/vgg16_bn/classifier.3/triplets_20mio"
modality = "dnn" 
params_interval = 500
checkpoint_interval = 50 
device_id = 0

# Model parameters
prior = "sslab"
init_dim = 150
n_epochs = 1000
stability_time = 500
batch_size = 256
non_zero_weights = 5
mc_samples = 20
beta = 0.24
lr = 0.001
seed = 0