# Path parameters
log_path = "./results"
identifier = "sslab_behavior"


# General parameters
triplet_path = "./data/triplets/behavior"
modality = "behavior" 
load_model = false
fresh = true
tensorboard = true
params_interval = 1
checkpoint_interval = 500  # we dont save the model in principle!
device_id = 0

# Model parameters
prior = "sslab"
init_dim = 100
n_epochs = 5
stability_time = 50
rnd_seed = 42
batch_size = 16384
non_zero_weights = 5
mc_samples = 50
beta = 1.0
scale = 3.0
lr = 0.001
