# TOML file to extract triplets from DNN representations
seed = 0 
k = 3

adaptive = false
similarity = "dot"
train_fraction = 0.9
n_samples = 20_000_000

out_path = "./data/Imagenet1k/densenet/global_pool/"
feature_path = "./data/triplets/Imagenet1k/densenet/global_pool/features.npy"
