# TOML file to extract triplets from DNN representations

seed = 0 
n_samples = 4_120_663
adaptive = false
k = 3
train_fraction = 0.9
out_path = "./data/triplets_dependent_human_intersection"
triplet_path = "./data/triplets/behavior/test_10.txt"
similarity = "dot"
feature_path = "./data/misc/intersection_dependent_human.npy"