# TOML file to extract triplets from DNN representations

# Sampling specifics
seed = 0 
n_samples = 1e4
extract = true
adaptive = false

# Data specifics
# In path can be anything. A path of images if we want to extract features
# or a path of features / activities if we want to extract triplets
in_path = "./data/things/images" 

# DNN Layer and Model to extract from
model_name = "vgg16_bn"
module_name = "classifier.3"
batch_size = 64